name:                infopv
version:             0.2.1
-- synopsis:
-- description:
license:             BSD3
license-file:        LICENSE
author:              Stefan Koppier, Wishnu Prasetya
-- maintainer:          s.koppier@students.uu.nl
-- copyright:
category:            Testing
build-type:          Simple
extra-source-files:  README.md
cabal-version:       >=1.10

executable infopv
  build-depends:       parser
                     , base >= 4.10
                     , z3
                     , transformers
                     , mtl
                     , optparse-applicative
                     , containers
                     , random
  -- location to z3 bin and lib:
  extra-lib-dirs:      /usr/lib/aarch64-linux-gnu
  main-is:             Main.hs
  hs-source-dirs:      app
  default-language:    Haskell2010
  default-extensions:  LambdaCase
                     , NamedFieldPuns
                     , BlockArguments
                     , TupleSections
                     , PatternSynonyms

benchmark verifier-bench
  type:              exitcode-stdio-1.0
  hs-source-dirs:    bench
  main-is:           Benchmark.hs
  build-depends:     base
                   , criterion
                   , parser
                   , z3
                   , transformers
                   , mtl
                   , containers
                   , random
  default-language: Haskell2010
  default-extensions: BangPatterns
  ghc-options: -O2

library parser
  exposed-modules:     GCLParser.Parser
                     , GCLParser.GCLDatatype
                     , GCLParser.PrettyPrint
                     , GCLInterpreter
                     , MuGCL
                     , GCLUtils
                     , GCLLexer.Token
                     , GCLLexer.Lexer
                     , ExamplesOfSemanticFunction
                     , Verifier.Checker
                     , Verifier.Stats
                     , Verifier.Tree
  -- other-extensions:
  build-depends:       base   >= 4.10
                     , array
                     , containers
                     , optparse-applicative
                     , pretty
                     , directory
                     , z3
                     , transformers
                     , mtl
                     , containers
                     , random
                     , deepseq
  hs-source-dirs:      src
  build-tools:         happy, alex
  default-language:    Haskell2010
  GHC-Options:         -Wall
  default-extensions:  LambdaCase
                     , NamedFieldPuns
                     , BlockArguments
                     , TupleSections
                     , PatternSynonyms
                     , DeriveGeneric
                     , DeriveAnyClass
